name: cypressTest

on:
  push:
    branches:
      - main  

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Start the app in background
        run: |
          npm start &
          npx wait-on http://localhost:3000
        env:
          PORT: 3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

