# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout your Cypress test repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # Start the Next.js server in the background
      - name: Start Next.js server
        run: npm start &

      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run


